name: "joamag/cleanup-hosted"
description: "Cleanups an hosted GitHub Runner environment"
inputs:
  remove-temp:
    description: "Should remove temporary directories"
    required: false
    default: "false"
  remove-home-cache:
    description: "Should remove home cache directories"
    required: false
    default: "true"
  remove-tools:
    description: "Should remove tools directories"
    required: false
    default: "true"
runs:
  using: "node12"
  main: "dist/index.js"
